<?php
/**
 * Apptha
*
* NOTICE OF LICENSE
*
* This source file is subject to the EULA
* that is bundled with this package in the file LICENSE.txt.
* It is also available through the world-wide-web at this URL:
* http://www.apptha.com/LICENSE.txt
*
* ==============================================================
*                 MAGENTO EDITION USAGE NOTICE
* ==============================================================
* This package designed for Magento COMMUNITY edition
* Apptha does not guarantee correct work of this extension
* on any other Magento edition except Magento COMMUNITY edition.
* Apptha does not provide extension support in case of
* incorrect edition usage.
* ==============================================================
*
* @category    Apptha
* @package     Apptha_Extendedmassaction
* @version     1.0.0
* @author      Apptha Team <developers@contus.in>
* @copyright   Copyright (c) 2014 Apptha. (http://www.apptha.com)
* @license     http://www.apptha.com/LICENSE.txt
*
*/ 
?>
<div id="<?php echo $this->getHtmlId() ?>">
<table cellspacing="0" cellpadding="0" class="massaction">
<tr>
    <td><?php if ($this->getUseSelectAll()):?>
        <a href="#" onclick="return <?php echo $this->getJsObjectName() ?>.selectAll()"><?php echo $this->__('Select All') ?></a>
        <span class="separator">|</span>
        <a href="#" onclick="return <?php echo $this->getJsObjectName() ?>.unselectAll()"><?php echo $this->__('Unselect All') ?></a>
        <span class="separator">|</span>
        <?php endif; ?>
        <a href="#" onclick="return <?php echo $this->getJsObjectName() ?>.selectVisible()"><?php echo $this->__('Select Visible') ?></a>
        <span class="separator">|</span>
        <a href="#" onclick="return <?php echo $this->getJsObjectName() ?>.unselectVisible()"><?php echo $this->__('Unselect Visible') ?></a>
        <span class="separator">|</span>
        <strong id="<?php echo $this->getHtmlId() ?>-count">0</strong> <?php echo $this->__('items selected') ?>
    </td>
    <td>
        <div class="right">
            <div class="entry-edit">
                <?php if ($this->getHideFormElement() !== true):?>
                <form action="" id="<?php echo $this->getHtmlId() ?>-form" method="post">
                <?php endif ?>
                    <?php echo $this->getBlockHtml('formkey')?>
                    <fieldset>
                        <span class="field-row">
                            <label><?php echo $this->__('Actions') ?></label>
                            <select id="<?php echo $this->getHtmlId() ?>-select" class="required-entry select absolute-advice local-validation">
                                <option value=""></option>
                                <?php foreach($this->getItems() as $_item): ?>
                                    <option value="<?php echo $_item->getId() ?>"<?php echo ($_item->getSelected() ? ' selected="selected"' : '')?>><?php echo $_item->getLabel() ?></option>
                                <?php endforeach; ?>
                            </select>
                        </span>
                        <span class="outer-span" id="<?php echo $this->getHtmlId() ?>-form-hiddens"></span>
                        <span class="outer-span" id="<?php echo $this->getHtmlId() ?>-form-additional"></span>
                        <span class="field-row">
                            <?php echo $this->getApplyButtonHtml() ?>
                        </span>
                    </fieldset>
                <?php if ($this->getHideFormElement() !== true):?>
                </form>
                <?php endif ?>
            </div>

            <div class="no-display">
            <?php foreach($this->getItems() as $_item): ?>
                <div id="<?php echo $this->getHtmlId() ?>-item-<?php echo $_item->getId() ?>-block">
                    <?php echo $_item->getAdditionalActionBlockHtml() ?>
                </div>
            <?php endforeach; ?>
            </div>
        </div>
    </td>
</tr>
</table>
<?php if(!$this->getParentBlock()->canDisplayContainer()): ?>
<script type="text/javascript">
    <?php echo $this->getJsObjectName() ?>.setGridIds('<?php echo $this->getGridIdsJson() ?>');
</script>
<?php endif; ?>
</div>
